ALTER TABLE projects DROP CONSTRAINT IF EXISTS chk_estado;
ALTER TABLE projects ADD CONSTRAINT chk_estado
    CHECK (estado IN ('PREPARACION', 'FINANCIAMIENTO', 'EJECUCION', 'FINALIZADO', 'CANCELADO', 'RECHAZADO'));
