[profile.default]
src = "contracts"
out = "out"
test = "test"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/"
]
solc = "0.8.20"
via-ir = true
optimizer = true
optimizer_runs = 200
libs = ["node_modules", "lib"]
