
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    email VARCHAR(100) UNIQUE,
    password_hash VARCHAR(255),
    saldo_idea DECIMAL(15,2) DEFAULT 0,
    saldo_usdt DECIMAL(15,2) DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    descripcion VARCHAR(300),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creador_id INTEGER NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    monto_requerido DECIMAL(15,2) NOT NULL,
    plazo TIMESTAMP NOT NULL,
    estado VARCHAR(50) NOT NULL,
    gobernanza_comunidad BOOLEAN DEFAULT FALSE,
    cupo_maximo_tokens INTEGER,
    valor_nominal_token DECIMAL(15,2),
    monto_recaudado DECIMAL(15,2),
    es_destacado BOOLEAN DEFAULT FALSE,
    fecha_boost TIMESTAMP,
    monto_boost DECIMAL(15,2),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS investments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    proyecto_id INTEGER NOT NULL,
    monto_idea DECIMAL(15,2) NOT NULL,
    sub_tokens_recibidos INTEGER NOT NULL,
    tx_hash VARCHAR(255),
    estado VARCHAR(50) DEFAULT 'completada',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subtokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id INTEGER NOT NULL UNIQUE,
    nombre VARCHAR(20) NOT NULL,
    simbolo VARCHAR(10) NOT NULL,
    suministro_total INTEGER NOT NULL,
    cupo_restante INTEGER NOT NULL,
    precio_actual DECIMAL(15,2) NOT NULL,
    precio_base DECIMAL(15,2),
    factor_volatilidad DECIMAL(10,4),
    contract_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_activos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    subtoken_id INTEGER NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_findings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id INTEGER NOT NULL,
    auditor_id INTEGER NOT NULL,
    kyb_url VARCHAR(2048) NOT NULL,
    resultado VARCHAR(20) NOT NULL,
    observaciones TEXT,
    tx_hash VARCHAR(66),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notificaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    read_at TIMESTAMP
);
