name: Backup Database

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get remove -y postgresql-client postgresql-client-common
          sudo apt-get autoremove -y
          sudo apt-get update
          sudo apt-get install -y gnupg2 wget lsb-release
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql.gpg
          echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Run Backup
        # Mantenemos tu env para consistencia, aunque pg_dump lee la URI directa
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          /usr/lib/postgresql/17/bin/pg_dump --verbose --no-owner --no-privileges -n public "${{ secrets.SUPABASE_DB_URL }}" -f backup.sql
      
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/889190443263/locations/global/workloadIdentityPools/gh-pool-tofu/providers/gh-provider-tofu'
          service_account: 'tofu-runner@project-1944cf83-7f15-4f33-89b.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload to GCS
        run: gcloud storage cp backup.sql gs://systeam/backups/backup-$(date +%Y%m%d).sql