name: Backup Database

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Run Backup
        # Esta variable PGPASSWORD le da al comando el "pase VIP" de autenticación
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          pg_dump --verbose --no-owner --no-privileges "${{ secrets.SUPABASE_DB_URL }}" -f backup.sql
      
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/889190443263/locations/global/workloadIdentityPools/gh-pool-tofu/providers/gh-provider-tofu'
          service_account: 'tofu-runner@project-1944cf83-7f15-4f33-89b.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload to GCS
        run: gcloud storage cp backup.sql gs://systeam/backups/backup-$(date +%Y%m%d).sql